import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";
import { WORKFLOWS } from "../src/data/workflows.js";
import { buildPipeline } from "../src/domain/pipeline.js";
import { seedExecutions } from "./seed.js";


const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.join(__dirname, "data");
const storeFile = path.join(dataDir, "store.json");

function clone(value) {
  return JSON.parse(JSON.stringify(value));
}

function atomicWrite(file, value) {
  const temp = `${file}.${process.pid}.tmp`;
  fs.writeFileSync(temp, JSON.stringify(value, null, 2), "utf8");
  fs.renameSync(temp, file);
}

function initialState() {
  const executions = clone(seedExecutions()).map((e) => ({
    ...e,
    status: e.status,
    cancelRequested: false,
    nextStepIndex: 0,
    maxAttempts: 3,
  }));
  return {
    version: 1,
    users: [],
    sessions: [],
    workflows: clone(WORKFLOWS),
    workflowVersions: WORKFLOWS.map((workflow) => ({
      id: id("wfv"),
      workflowId: workflow.id,
      version: workflow.version,
      status: "published",
      createdAt: new Date().toISOString(),
      createdBy: { id: "system", name: "Altair", role: "system" },
      definition: clone(workflow),
    })),
    executions,
    notifications: clone(executions.flatMap((e) => e.status === "pending_approval" ? [{ id: `n-${e.id}-approve`, type: "approval_required", title: "Approval required", message: `${e.workflowId} is waiting for approval.`, at: e.updatedAt, read: false, link: { view: "execution", id: e.id } }] : [])),
    audit: executions.flatMap((e) => e.events.map((event) => ({
      ...event,
      executionId: e.id,
      workflowId: e.workflowId,
    }))),
    jobs: [],
    idempotency: [],
  };
}

function repairDemoIntegrationFailures(state) {
  if (process.env.ALTAIR_DEMO_MODE === "false") return state;
  let changed = false;
  const now = new Date().toISOString();

  for (const ex of state.executions || []) {
    if (ex.lastError?.code !== "integration_not_configured") continue;
    const workflow = state.workflows.find((w) => w.id === ex.workflowId);
    if (!workflow) continue;
    const pipeline = buildPipeline(workflow);
    const stepIndex = Math.max(0, pipeline.findIndex((node) => node.id === ex.currentNodeId));
    const jobExists = (state.jobs || []).some((job) => job.executionId === ex.id && ["queued", "running"].includes(job.status));
    ex.status = "retrying";
    ex.lastError = null;
    ex.updatedAt = now;
    if (!jobExists) {
      state.jobs.push({
        id: `demo-repair-${ex.id}-${Date.now()}`,
        executionId: ex.id,
        stepIndex,
        attempt: (ex.retryCount || 0) + 1,
        status: "queued",
        availableAt: Date.now(),
        createdAt: now,
      });
    }
    // Remove stale failure notifications generated by the old unconfigured adapter.
    state.notifications = (state.notifications || []).filter((n) => n.link?.id !== ex.id || !String(n.message || "").includes("Integration adapter"));
    changed = true;
  }
  return changed ? state : null;
}

export function ensureStore() {
  fs.mkdirSync(dataDir, { recursive: true });
  if (!fs.existsSync(storeFile)) {
    atomicWrite(storeFile, initialState());
    return;
  }
  // If the user previously ran a version that required a real external adapter,
  // repair those demo failures automatically so reopening the project is clean.
  const state = JSON.parse(fs.readFileSync(storeFile, "utf8"));
  const repaired = repairDemoIntegrationFailures(state);
  if (repaired) atomicWrite(storeFile, repaired);
}

export function readStore() {
  ensureStore();
  return JSON.parse(fs.readFileSync(storeFile, "utf8"));
}

export function writeStore(state) {
  atomicWrite(storeFile, state);
}

export function updateStore(mutator) {
  const state = readStore();
  const result = mutator(state) || state;
  writeStore(result);
  return result;
}

export function id(prefix) {
  return `${prefix}-${crypto.randomUUID()}`;
}

export { storeFile };
