from __future__ import annotations

from datetime import datetime
from typing import Any, Self

from pydantic import BaseModel, ConfigDict, Field, model_validator

from ecosystem.applications.arcturus.contracts.shared.base_models import (
    ContractEnvelope,
    SimulationContext,
)


class SyntheticGenerationRequest(ContractEnvelope):
    """
    Request contract for deterministic synthetic-data generation.

    SimulationContext is inherited through ContractEnvelope and remains
    the canonical source for run_id, trace_id, experiment_id, global_seed,
    created_at, and run-specific configuration.
    """

    model_config = ConfigDict(extra="forbid")

    context: SimulationContext

    requested_artifact_count: int | None = Field(
        default=None,
        ge=1,
        description=(
            "Optional bounded artifact count requested for this generation run. "
            "If omitted, the generation service resolves the count from its "
            "approved local/default configuration."
        ),
    )

    requested_artifact_types: list[str] = Field(
        default_factory=list,
        description=(
            "Optional artifact families requested for the generation run. "
            "An empty list allows the generation service to use its approved "
            "Part-3 artifact subset."
        ),
    )


class SyntheticRelationshipContract(BaseModel):
    """
    Typed relationship emitted with generated synthetic enterprise information.

    The source is always a generated synthetic artifact. The target may be
    another generated artifact or an upstream organizational entity referenced
    through its canonical identifier.
    """

    model_config = ConfigDict(extra="forbid")

    source_artifact_id: str = Field(..., min_length=1)
    target_id: str = Field(..., min_length=1)
    target_type: str = Field(..., min_length=1)
    relationship_type: str = Field(..., min_length=1)

    metadata: dict[str, Any] = Field(default_factory=dict)


class SyntheticArtifactContract(BaseModel):
    """
    Contract representation of one generated synthetic enterprise artifact.

    The platform owns the generated artifact, while references to enterprise,
    workforce, department, project, and workflow objects remain references to
    contracts owned by their respective Arcturus platforms.
    """

    model_config = ConfigDict(extra="forbid")

    artifact_id: str = Field(
        ...,
        min_length=1,
        description="Synthetic Data owned identifier for this artifact.",
    )

    artifact_type: str = Field(
        ...,
        min_length=1,
        description="Artifact family/type represented by this payload.",
    )

    content: dict[str, Any] = Field(
        default_factory=dict,
        description="Structured synthetic artifact content.",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Artifact metadata generated by the Synthetic Data Platform.",
    )

    lifecycle_state: str = Field(
        ...,
        min_length=1,
        description="Current lifecycle state of the generated artifact.",
    )

    version: int = Field(
        default=1,
        ge=1,
        description="Artifact version within the synthetic dataset.",
    )

    owner_entity_id: str | None = Field(
        default=None,
        description="Canonical enterprise entity reference when applicable.",
    )

    workforce_participant_id: str | None = Field(
        default=None,
        description="Canonical workforce participant reference when applicable.",
    )

    department_id: str | None = Field(
        default=None,
        description="Canonical department reference when applicable.",
    )

    business_function_id: str | None = Field(
        default=None,
        description="Canonical business-function reference when applicable.",
    )

    project_id: str | None = Field(
        default=None,
        description="Canonical project reference when applicable.",
    )

    workflow_id: str | None = Field(
        default=None,
        description="Canonical workflow/process reference when applicable.",
    )

    created_at: datetime = Field(
        ...,
        description=(
            "Artifact generation timestamp. The generation service must create "
            "this deterministically from the run context rather than relying "
            "on an uncontrolled wall-clock default."
        ),
    )

    provenance: dict[str, Any] = Field(
        ...,
        min_length=1,
        description="Trace information describing how this artifact was generated.",
    )


class SyntheticGenerationResult(ContractEnvelope):
    """
    Outbound handoff from Synthetic Data to Simulation Runtime.

    Runtime correlation identifiers are intentionally not duplicated here.
    Maaz can obtain them from:

        result.context.run_id
        result.context.trace_id
        result.context.experiment_id
        result.context.global_seed
    """

    model_config = ConfigDict(extra="forbid")

    context: SimulationContext

    artifacts: list[SyntheticArtifactContract] = Field(
        ...,
        min_length=1,
        description=(
            "Successfully generated synthetic artifacts. "
            "A successful result must contain at least one artifact."
        ),
    )

    relationships: list[SyntheticRelationshipContract] = Field(
        default_factory=list,
        description="Relationships involving generated synthetic artifacts.",
    )

    deterministic_fingerprint: str = Field(
        ...,
        min_length=1,
        description=(
            "Stable fingerprint of the canonical generated output used for "
            "same-context and same-seed reproducibility verification."
        ),
    )

    @model_validator(mode="after")
    def validate_internal_integrity(self) -> Self:
        artifact_ids = [artifact.artifact_id for artifact in self.artifacts]

        if len(artifact_ids) != len(set(artifact_ids)):
            raise ValueError(
                "artifact_id values must be unique within SyntheticGenerationResult"
            )

        generated_artifact_ids = set(artifact_ids)

        unknown_sources = {
            relationship.source_artifact_id
            for relationship in self.relationships
            if relationship.source_artifact_id not in generated_artifact_ids
        }

        if unknown_sources:
            unknown = ", ".join(sorted(unknown_sources))
            raise ValueError(
                "relationship source_artifact_id must reference a generated "
                f"artifact. Unknown source IDs: {unknown}"
            )

        return self


__all__ = [
    "SyntheticGenerationRequest",
    "SyntheticArtifactContract",
    "SyntheticRelationshipContract",
    "SyntheticGenerationResult",
]