"""
test_day8_integration.py

Part-7 of the roadmap: "System Testing, Evaluation & Working
Integration". Days 4-7 each tested their own engine in isolation.
Today's job is different: prove the WHOLE pipeline actually works
together end to end, and prove the system fails gracefully when
given bad input - not just when given good input.

Two sections:
    A. Functional/Integration Testing - the full real pipeline,
       start to finish, on realistic data.
    B. Failure Testing - malformed input, missing resources, edge
       cases that a real user (or a bug) could actually hit.
"""

import os
import uuid

import pytest
from fastapi.testclient import TestClient

os.environ.setdefault("TESTING", "1")

from .main import app  # noqa: E402


@pytest.fixture
def client():
    with TestClient(app) as c:
        yield c


# ============================================================
# A. FULL PIPELINE INTEGRATION TEST
# ============================================================

def test_full_pipeline_end_to_end(client):
    """
    Walks the entire roadmap lifecycle in one test, using two
    realistic organizational signals worded to trigger the same
    dimensions:

        Signal -> Impact -> Pattern -> Future Model
        -> Candidate Capability -> Intelligence Trace

    This is the test that actually proves Day 4 through Day 7 connect
    to each other correctly, not just that each one works alone.
    """
    description = (
        "Company X flattened its management structure, removing a layer "
        "of middle management and giving teams direct decision-making "
        "authority over their own hiring and daily operations."
    )

    # Step 1: ingest two similarly-worded real-world-style signals
    tag_a, tag_b = uuid.uuid4().hex[:6], uuid.uuid4().hex[:6]
    signal_a = client.post(
        "/signals?check_duplicates=false",
        json={"title": f"Flattened structure {tag_a}", "description": description, "source": "integration-test"},
    ).json()
    signal_b = client.post(
        "/signals?check_duplicates=false",
        json={"title": f"Flattened structure {tag_b}", "description": description, "source": "integration-test"},
    ).json()
    assert signal_a["id"] != signal_b["id"]

    # Step 2: evidence can be attached to a real signal
    evidence = client.post(
        "/evidence",
        json={
            "signal_id": signal_a["id"],
            "description": "Org chart diff showing removed management layer.",
            "source_reference": "internal report",
        },
    )
    assert evidence.status_code == 200

    # Step 3: impact analysis (Day 4)
    impacts_a = client.post(f"/signals/{signal_a['id']}/analyze").json()
    impacts_b = client.post(f"/signals/{signal_b['id']}/analyze").json()
    assert len(impacts_a) > 0
    assert len(impacts_b) > 0
    assert {i["dimension_id"] for i in impacts_a} == {i["dimension_id"] for i in impacts_b}

    # Step 4: pattern detection (Day 5)
    client.post("/patterns/detect")
    rels_a = client.get(f"/relationships?source_id={signal_a['id']}").json()
    pattern_id = next(r["target_id"] for r in rels_a if r["target_type"] == "pattern")
    pattern = client.get(f"/patterns").json()
    assert any(p["id"] == pattern_id for p in pattern)

    # Step 5: future model built from the pattern (Day 6)
    model = client.post("/models/build", json={"pattern_ids": [pattern_id]}).json()
    assert model["confidence"] == "hypothesized"
    support = client.get(f"/models/{model['id']}/support").json()
    assert any(s["source_id"] == pattern_id for s in support)

    # Step 6: candidate capability suggested from the model (Day 7)
    capability = client.post("/capabilities/build", json={"model_id": model["id"]}).json()
    assert capability["status"] == "candidate"  # never auto-approved

    # Step 7: the full trail is retrievable from a single signal
    trace = client.get(f"/intelligence/trace/{signal_a['id']}").json()
    assert trace["signal"]["id"] == signal_a["id"]
    assert len(trace["impacts"]) > 0
    assert any(p["id"] == pattern_id for p in trace["patterns"])
    assert any(m["id"] == model["id"] for m in trace["models"])
    assert any(c["id"] == capability["id"] for c in trace["candidate_capabilities"])

    # Step 8: evidence state discipline held throughout the whole run -
    # nothing generated by the engines claims to be more certain than
    # it actually is
    assert all(i["confidence"] == "inferred" for i in impacts_a)
    assert pattern_id in [p["id"] for p in pattern]
    assert model["confidence"] == "hypothesized"


# ============================================================
# B. FAILURE / EDGE CASE TESTING
# ============================================================

def test_malformed_signal_missing_required_field_returns_422(client):
    response = client.post("/signals?check_duplicates=false", json={"description": "no title given"})
    assert response.status_code == 422


def test_evidence_for_nonexistent_signal_returns_404_or_error(client):
    response = client.post(
        "/evidence",
        json={"signal_id": "does-not-exist", "description": "y", "source_reference": "x"},
    )
    assert response.status_code in (404, 400)


def test_analyze_nonexistent_signal_returns_404(client):
    assert client.post("/signals/does-not-exist/analyze").status_code == 404


def test_analyze_signal_with_no_matching_keywords_still_returns_200(client):
    """A signal that matches NO dimension keywords is still valid input -
    the engine should return an empty impact list, not error out."""
    signal = client.post(
        "/signals?check_duplicates=false",
        json={"title": "Weather note", "description": "It rained yesterday.", "source": "t"},
    ).json()
    response = client.post(f"/signals/{signal['id']}/analyze")
    assert response.status_code == 200
    assert response.json() == []


def test_detect_patterns_with_no_signals_returns_empty_list(client):
    """Running pattern detection on a database with zero analyzed
    signals should return an empty list, not crash."""
    response = client.post("/patterns/detect")
    assert response.status_code == 200
    assert isinstance(response.json(), list)


def test_build_model_with_empty_pattern_list_returns_404(client):
    response = client.post("/models/build", json={"pattern_ids": []})
    assert response.status_code == 404


def test_build_capability_missing_model_returns_404(client):
    response = client.post("/capabilities/build", json={"model_id": "fake"})
    assert response.status_code == 404


def test_trace_missing_signal_returns_404(client):
    response = client.get("/intelligence/trace/does-not-exist")
    assert response.status_code == 404


def test_duplicate_signal_still_blocked_by_default(client):
    """Confirms Day 2's duplicate detection is still active and wasn't
    accidentally weakened by anything added in Days 4-7."""
    payload = {
        "title": "Duplicate check integration test",
        "description": "This exact wording should be flagged as a duplicate on the second attempt.",
        "source": "integration-test",
    }
    first = client.post("/signals", json=payload)
    assert first.status_code == 200
    second = client.post("/signals", json=payload)
    assert second.status_code == 409


def test_force_reanalysis_does_not_corrupt_relationship_count(client):
    """Re-running impact analysis with force=true should add impacts
    and relationships, never remove or corrupt existing ones."""
    signal = client.post(
        "/signals?check_duplicates=false",
        json={"title": "Reanalysis test", "description": "New governance policy changed board approval.", "source": "t"},
    ).json()
    client.post(f"/signals/{signal['id']}/analyze")
    before = len(client.get(f"/relationships?source_id={signal['id']}").json())

    client.post(f"/signals/{signal['id']}/analyze?force=true")
    after = len(client.get(f"/relationships?source_id={signal['id']}").json())

    assert after > before
