"""
Arcturus Governance — markdown_reporter.py
==========================================
Governance Owner: Hashim Ali Khan (@Hashimali-khan)
Day 3 Deliverable: Formats compliance scan findings into a structured,
PR-ready markdown document that can be posted as a GitHub comment or
stored as a CI artifact.

This module is the single rendering layer for all Arcturus governance output.
No other module should produce raw markdown for PR comments — they must
delegate to emit_markdown_report().
"""
from __future__ import annotations

import textwrap
from datetime import datetime, timezone
from pathlib import Path

from ecosystem.applications.arcturus.src.governance.compliance_scanner import (
    ComplianceScanReport,
)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def emit_markdown_report(
    report: ComplianceScanReport,
    *,
    output_path: Path | str | None = None,
) -> str:
    """
    Render a ComplianceScanReport as a structured GitHub Flavored Markdown
    document.

    Parameters
    ----------
    report:
        The compliance report produced by ArcturusComplianceScanner.run_full_scan().
    output_path:
        If provided, the rendered markdown is also written to this file path.
        The parent directory is created if it does not already exist.

    Returns
    -------
    str
        The complete markdown string.
    """
    md = _render(report)

    if output_path is not None:
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(md, encoding="utf-8")

    return md


# ---------------------------------------------------------------------------
# Rendering Helpers
# ---------------------------------------------------------------------------


def _render(report: ComplianceScanReport) -> str:
    """Build the full markdown string from a ComplianceScanReport."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    verdict_emoji = "✅" if report.is_compliant else "❌"
    verdict_label = "COMPLIANT" if report.is_compliant else "NON-COMPLIANT"

    sections: list[str] = [
        f"# {verdict_emoji} Arcturus Governance Gate — {verdict_label}",
        f"",
        f"> **Scan timestamp:** {now}  ",
        f"> **Overall status:** `{verdict_label}`",
        f"",
        "---",
        "",
        "## 1. Path Boundary Check (§2.2)",
        "",
        _render_path_section(report),
        "",
        "---",
        "",
        "## 2. Import Boundary Check (§2.1)",
        "",
        _render_import_section(report),
        "",
        "---",
        "",
        "## 3. Secret Pattern Scan",
        "",
        _render_secret_section(report),
        "",
        "---",
        "",
        "## 4. Working Tree Dirtiness",
        "",
        _render_tree_section(report),
        "",
        "---",
        "",
        "## 5. Verdict Summary",
        "",
        _render_verdict_table(report),
        "",
        "---",
        "",
        "_Report generated by Arcturus Governance Gate — "
        "Hashim Ali Khan (@Hashimali-khan)_",
    ]

    return "\n".join(sections)


def _render_path_section(report: ComplianceScanReport) -> str:
    r = report.path_result
    if r.is_compliant:
        return (
            f"**Status:** ✅ Pass  \n"
            f"**Files checked:** {r.total_files_checked}  \n"
            f"**Violations:** 0"
        )
    lines = [
        f"**Status:** ❌ Fail  ",
        f"**Files checked:** {r.total_files_checked}  ",
        f"**Violations:** {len(r.violations)}",
        "",
        "| File | Reason |",
        "| --- | --- |",
    ]
    for v in r.violations:
        lines.append(f"| `{_truncate(v.offending_path)}` | {v.reason} |")
    return "\n".join(lines)


def _render_import_section(report: ComplianceScanReport) -> str:
    r = report.import_result
    if r.is_compliant:
        return (
            f"**Status:** ✅ Pass  \n"
            f"**Files checked:** {r.scanned_files}  \n"
            f"**Forbidden imports:** 0"
        )
    lines = [
        f"**Status:** ❌ Fail  ",
        f"**Files checked:** {r.scanned_files}  ",
        f"**Forbidden imports:** {len(r.import_violations)}",
        "",
        "| File | Line | Import |",
        "| --- | --- | --- |",
    ]
    for v in r.import_violations:
        lines.append(
            f"| `{_truncate(v.file_path)}` | {v.line_number} "
            f"| `{_truncate(v.import_statement, 60)}` |"
        )
    return "\n".join(lines)


def _render_secret_section(report: ComplianceScanReport) -> str:
    r = report.secret_result
    if not r.secret_hits:
        return (
            f"**Status:** ✅ Pass  \n"
            f"**Files checked:** {r.scanned_files}  \n"
            f"**Secret patterns found:** 0"
        )
    lines = [
        f"**Status:** ❌ Fail  ",
        f"**Files checked:** {r.scanned_files}  ",
        f"**Secret patterns found:** {len(r.secret_hits)}",
        "",
        "| File | Line | Pattern |",
        "| --- | --- | --- |",
    ]
    for s in r.secret_hits:
        lines.append(
            f"| `{_truncate(s.file_path)}` | {s.line_number} "
            f"| `{s.matched_pattern}` |"
        )
    return "\n".join(lines)


def _render_tree_section(report: ComplianceScanReport) -> str:
    if not report.tree_is_dirty:
        return "**Status:** ✅ Pass — working tree is clean"
    lines = [
        f"**Status:** ❌ Fail — {len(report.dirty_files)} uncommitted file(s)",
        "",
        "```",
    ]
    lines.extend(report.dirty_files[:30])
    if len(report.dirty_files) > 30:
        lines.append(f"… and {len(report.dirty_files) - 30} more")
    lines.append("```")
    return "\n".join(lines)


def _render_verdict_table(report: ComplianceScanReport) -> str:
    def row(name: str, passed: bool) -> str:
        icon = "✅ Pass" if passed else "❌ Fail"
        return f"| {name} | {icon} |"

    return "\n".join([
        "| Check | Result |",
        "| --- | --- |",
        row("Path Boundaries (§2.2)", report.path_result.is_compliant),
        row("Import Boundaries (§2.1)", report.import_result.is_compliant),
        row("Secret Pattern Scan", not bool(report.secret_result.secret_hits)),
        row("Working Tree Clean", not report.tree_is_dirty),
        row("**Overall**", report.is_compliant),
    ])


def _truncate(text: str, max_len: int = 80) -> str:
    """Truncate long paths/imports for table readability."""
    if len(text) <= max_len:
        return text
    return "…" + text[-(max_len - 1):]
