from fastapi.testclient import TestClient

from security_quality_platform.main import app


client = TestClient(app)


ASSESSMENT_PAYLOAD = {
    "requester": "mustafa",
    "requester_role": "security-quality",
    "target_platform": "Sentinel",
    "target_capability": "DevSecOps",
    "environment": "test",
    "scope": "Verify evidence integrity",
    "risk_tier": "TIER_1",
    "verification_depth": "DEEP",
    "responsible_owner": "devsecops-owner",
    "verification_authority": "security-quality",
    "acceptance_criteria": "Evidence must be integrity verified",
}


VALID_HASH = "a" * 64
INVALID_HASH = "b" * 64


def create_assessment():
    response = client.post(
        "/api/v1/assessments",
        json=ASSESSMENT_PAYLOAD,
    )
    assert response.status_code == 201
    return response.json()["id"]


def test_create_and_verify_evidence():
    assessment_id = create_assessment()

    create_response = client.post(
        f"/api/v1/assessments/{assessment_id}/evidence",
        json={
            "evidence_type": "security-test-result",
            "source": "pytest",
            "storage_reference": "artifacts/security-result.json",
            "sha256": VALID_HASH,
            "provenance": "Generated by controlled security verification",
            "collected_by": "security-quality",
        },
    )

    assert create_response.status_code == 201

    evidence = create_response.json()

    assert evidence["integrity_verified"] is False
    assert evidence["sha256"] == VALID_HASH

    verify_response = client.post(
        f"/api/v1/evidence/{evidence['id']}/verify",
        json={
            "observed_sha256": VALID_HASH,
            "verified_by": "independent-verifier",
        },
    )

    assert verify_response.status_code == 200
    assert verify_response.json()["integrity_verified"] is True


def test_tampered_evidence_is_rejected():
    assessment_id = create_assessment()

    create_response = client.post(
        f"/api/v1/assessments/{assessment_id}/evidence",
        json={
            "evidence_type": "security-test-result",
            "source": "pytest",
            "storage_reference": "artifacts/security-result.json",
            "sha256": VALID_HASH,
            "provenance": "Generated by controlled security verification",
            "collected_by": "security-quality",
        },
    )

    evidence_id = create_response.json()["id"]

    verify_response = client.post(
        f"/api/v1/evidence/{evidence_id}/verify",
        json={
            "observed_sha256": INVALID_HASH,
            "verified_by": "independent-verifier",
        },
    )

    assert verify_response.status_code == 409
    assert "integrity verification failed" in verify_response.json()["detail"]
