"""
Future Organization Runtime — HTTP API (Din 3 / Part 3).

This closes the single largest blocker identified in Part 1/Part 2:
there was no network-accessible interface. Every endpoint here is a thin
wrapper around the already-verified service functions from Days 2-10 —
no new business logic is introduced here, only real network exposure of
what Part 1 confirmed as REAL.

Honest scope note: this makes Zeeshan's runtime genuinely live and
callable over HTTP. It does NOT connect to Kanwal's or Hasnain's actual
platforms, since those don't exist in this environment — this server IS
the real, honest boundary those platforms would call into once they
exist. Nothing here simulates a connection to them.

Run: uvicorn app.api:app --reload --port 8000
Docs: http://localhost:8000/docs (auto-generated by FastAPI)
"""
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional

from app.database import init_db, get_session
from app.services.organization_service import create_organization, create_organizational_unit
from app.services.role_service import define_human_role, define_agent_role, grant_capability_to_agent
from app.services.capability_service import assign_capability, define_responsibility
from app.services.workflow_service import create_workflow, create_task
from app.services.governance_service import create_policy, receive_governance_rules
from app.services.agent_engine import run_agent_task, resume_agent_task, TaskExecutionError
from app.services.decision_service import approve_decision, reject_decision
from app.services import query_service
from app.models import Organization, AgentRole, Task
from app.models.governance import Decision

app = FastAPI(
    title="Future Organization Runtime API",
    description="Live HTTP boundary for the Future Organization Engineering Platform. "
                "Wraps the verified Days 2-10 service layer; introduces no new business logic.",
    version="1.0",
)

# CORS: permissive for local development only, so the live dashboard
# (served as a separate static file) can call this API from a browser.
# Honest note: this is NOT a production CORS policy — it allows any
# origin, which is appropriate only alongside the "no authentication"
# limitation already documented in the Din 3/4 report, not a separate
# new risk being introduced quietly.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


def db():
    return get_session()


@app.on_event("startup")
def on_startup():
    init_db()


# ---------- Request/response models ----------

class CreateOrgRequest(BaseModel):
    name: str
    mission: Optional[str] = None
    owner_id: Optional[str] = None


class CreateUnitRequest(BaseModel):
    organization_id: str
    name: str


class CreateCapabilityRequest(BaseModel):
    organization_id: str
    name: str
    description: Optional[str] = None


class CreateWorkflowRequest(BaseModel):
    capability_id: str
    name: str


class CreateTaskRequest(BaseModel):
    workflow_id: str
    title: str
    assignee_id: Optional[str] = None
    assignee_type: Optional[str] = None


class DefineAgentRoleRequest(BaseModel):
    unit_id: str
    title: str


class GrantCapabilityRequest(BaseModel):
    agent_role_id: str
    capability_id: str
    granted_by: Optional[str] = None


class RunAgentTaskRequest(BaseModel):
    agent_role_id: str
    task_id: str


class ApproveDecisionRequest(BaseModel):
    approver_id: str


class GovernanceRuleInput(BaseModel):
    name: str
    rule: str
    requires_approval: bool = False
    applies_to_capability_id: Optional[str] = None


class ReceiveGovernanceRulesRequest(BaseModel):
    organization_id: str
    rules: list[GovernanceRuleInput]
    source: str = "kanwal"


# ---------- Health ----------

@app.get("/health")
def health():
    """Honest liveness check — real, not decorative."""
    return {"status": "live", "service": "future-organization-runtime"}


# ---------- Write endpoints (real state mutation) ----------

@app.post("/organizations")
def api_create_organization(req: CreateOrgRequest):
    session = db()
    try:
        org = create_organization(session, name=req.name, mission=req.mission, owner_id=req.owner_id)
        return {"organization_id": org.id, "name": org.name, "lifecycle_state": org.lifecycle_state.value}
    finally:
        session.close()


@app.post("/units")
def api_create_unit(req: CreateUnitRequest):
    session = db()
    try:
        unit = create_organizational_unit(session, organization_id=req.organization_id, name=req.name)
        return {"unit_id": unit.id, "name": unit.name, "organization_id": unit.organization_id}
    finally:
        session.close()


@app.post("/capabilities")
def api_create_capability(req: CreateCapabilityRequest):
    session = db()
    try:
        cap = assign_capability(session, organization_id=req.organization_id, name=req.name,
                                 description=req.description)
        return {"capability_id": cap.id, "name": cap.name}
    finally:
        session.close()


@app.post("/workflows")
def api_create_workflow(req: CreateWorkflowRequest):
    session = db()
    try:
        wf = create_workflow(session, capability_id=req.capability_id, name=req.name)
        return {"workflow_id": wf.id, "name": wf.name}
    finally:
        session.close()


@app.post("/tasks")
def api_create_task(req: CreateTaskRequest):
    session = db()
    try:
        task = create_task(session, workflow_id=req.workflow_id, title=req.title,
                            assignee_id=req.assignee_id, assignee_type=req.assignee_type)
        return {"task_id": task.id, "title": task.title, "status": task.status}
    finally:
        session.close()


@app.post("/agent-roles")
def api_define_agent_role(req: DefineAgentRoleRequest):
    session = db()
    try:
        role = define_agent_role(session, unit_id=req.unit_id, title=req.title)
        return {"agent_role_id": role.id, "title": role.title}
    finally:
        session.close()


@app.post("/agent-roles/grant-capability")
def api_grant_capability(req: GrantCapabilityRequest):
    session = db()
    try:
        grant = grant_capability_to_agent(session, agent_role_id=req.agent_role_id,
                                           capability_id=req.capability_id, granted_by=req.granted_by)
        return {"grant_id": grant.id, "agent_role_id": grant.agent_role_id, "capability_id": grant.capability_id}
    finally:
        session.close()


@app.post("/agent-tasks/run")
def api_run_agent_task(req: RunAgentTaskRequest):
    """
    Real execution trigger over HTTP. Uses the default (no-op) planner/
    tool_executor, since no real AI/ML connection exists (per Part 1/2
    findings) — this endpoint proves live network-triggered execution,
    not simulated AI reasoning.
    """
    session = db()
    try:
        agent_role = session.get(AgentRole, req.agent_role_id)
        task = session.get(Task, req.task_id)
        if not agent_role or not task:
            raise HTTPException(status_code=404, detail="agent_role or task not found")
        result = run_agent_task(session, agent_role, task)
        return {"task_id": result.id, "status": result.status, "result": result.result,
                "retry_count": result.retry_count}
    finally:
        session.close()


@app.post("/decisions/{decision_id}/approve")
def api_approve_decision(decision_id: str, req: ApproveDecisionRequest):
    session = db()
    try:
        decision = session.get(Decision, decision_id)
        if not decision:
            raise HTTPException(status_code=404, detail="decision not found")
        try:
            approved = approve_decision(session, decision, approver_id=req.approver_id)
        except ValueError as e:
            raise HTTPException(status_code=409, detail=str(e))
        return {"decision_id": approved.id, "status": approved.status, "approver_id": approved.approver_id}
    finally:
        session.close()


@app.post("/decisions/{decision_id}/resume")
def api_resume_task(decision_id: str, agent_role_id: str):
    session = db()
    try:
        decision = session.get(Decision, decision_id)
        agent_role = session.get(AgentRole, agent_role_id)
        if not decision or not agent_role:
            raise HTTPException(status_code=404, detail="decision or agent_role not found")
        try:
            result = resume_agent_task(session, decision, agent_role)
        except ValueError as e:
            raise HTTPException(status_code=409, detail=str(e))
        return {"task_id": result.id, "status": result.status, "result": result.result}
    finally:
        session.close()


@app.post("/governance/receive-rules")
def api_receive_governance_rules(req: ReceiveGovernanceRulesRequest):
    """The real Kanwal integration point (Part 2, Section 9) — now network-callable."""
    session = db()
    try:
        rules = [r.model_dump() for r in req.rules]
        policies = receive_governance_rules(session, organization_id=req.organization_id,
                                             rules=rules, source=req.source)
        return {"policies_created": [p.id for p in policies]}
    finally:
        session.close()


# ---------- Read endpoints (real, live-queried state) ----------

@app.get("/organizations/{organization_id}/state")
def api_get_organization_state(organization_id: str):
    session = db()
    try:
        org = session.get(Organization, organization_id)
        if not org:
            raise HTTPException(status_code=404, detail="organization not found")
        return query_service.get_organization_state(session, org)
    finally:
        session.close()


@app.get("/tasks/{task_id}")
def api_get_task_status(task_id: str):
    session = db()
    try:
        result = query_service.get_task_status(session, task_id)
        if "error" in result:
            raise HTTPException(status_code=404, detail=result["error"])
        return result
    finally:
        session.close()


@app.get("/agent-roles/{agent_role_id}/status")
def api_get_agent_status(agent_role_id: str):
    session = db()
    try:
        agent = session.get(AgentRole, agent_role_id)
        if not agent:
            raise HTTPException(status_code=404, detail="agent_role not found")
        return query_service.get_agent_status(session, agent)
    finally:
        session.close()


@app.get("/organizations/{organization_id}/decisions/pending")
def api_get_pending_decisions(organization_id: str):
    session = db()
    try:
        return query_service.get_pending_decisions(session, organization_id)
    finally:
        session.close()


@app.get("/organizations/{organization_id}/escalations")
def api_get_escalations(organization_id: str):
    session = db()
    try:
        return query_service.get_unresolved_escalations(session, organization_id)
    finally:
        session.close()


@app.get("/organizations/{organization_id}/memory")
def api_get_memory(organization_id: str):
    session = db()
    try:
        return query_service.get_organizational_memory(session, organization_id)
    finally:
        session.close()
